### ISSUE TITLE
FreeBSD/*BSD support missing

### ISSUE THREAD

**Issue by cederom** [NXPmicro/pypemicro#7]
Hello world :-)

This `pypemicro` is now part of the https://github.com/pyocd/pyOCD and became a blocker on FreeBSD platform, probably other *BSD platforms (i.e. OpenBSD, NetBSD, etc), and other platforms not on the list of: Windows, Linux, Darwin.

* I will try to fix the OS detection mechanism.
```
(venv37zephyr) pyocd list
0001557:CRITICAL:__main__:Unable to determinate running operation system (FreeBSD)
Traceback (most recent call last):
  File "/home/x/usr/local/venv37zephyr/lib/python3.7/site-packages/pypemicro/pemicro.py", line 401, in get_pemicro_lib
    libs_list = PyPemicro.get_pemicro_lib_list(dllpath=dllpath)
  File "/home/x/usr/local/venv37zephyr/lib/python3.7/site-packages/pypemicro/pemicro.py", line 142, in get_pemicro_lib_list
    lib_name = PyPemicro.get_library_name()
  File "/home/x/usr/local/venv37zephyr/lib/python3.7/site-packages/pypemicro/pemicro.py", line 99, in get_library_name
    raise PEMicroException(f"Unable to determinate running operation system ({system_name})")
pypemicro.pemicro.PEMicroException: Unable to determinate running operation system (FreeBSD)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/x/usr/local/venv37zephyr/lib/python3.7/site-packages/pypemicro/pemicro.py", line 419, in list_ports
    lib = PyPemicro.get_pemicro_lib()
  File "/home/x/usr/local/venv37zephyr/lib/python3.7/site-packages/pypemicro/pemicro.py", line 407, in get_pemicro_lib
    raise PEMicroException(str(exc))
pypemicro.pemicro.PEMicroException: Unable to determinate running operation system (FreeBSD)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/x/usr/local/venv37zephyr/lib/python3.7/site-packages/pyocd_pemicro-1.0.4-py3.7.egg/pyocd_pemicro/pemicro_probe.py", line 81, in get_all_connected_probes
    port_list = pemicro.list_ports()
  File "/home/x/usr/local/venv37zephyr/lib/python3.7/site-packages/pypemicro/pemicro.py", line 421, in list_ports
    raise PEMicroException(str(exc))
pypemicro.pemicro.PEMicroException: Unable to determinate running operation system (FreeBSD)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/x/usr/local/venv37zephyr/lib/python3.7/site-packages/pyocd-0.30.4.dev31-py3.7.egg/pyocd/__main__.py", line 150, in run
    status = cmd.invoke()
  File "/home/x/usr/local/venv37zephyr/lib/python3.7/site-packages/pyocd-0.30.4.dev31-py3.7.egg/pyocd/subcommands/list_cmd.py", line 93, in invoke
    ConnectHelper.list_connected_probes()
  File "/home/x/usr/local/venv37zephyr/lib/python3.7/site-packages/pyocd-0.30.4.dev31-py3.7.egg/pyocd/core/helpers.py", line 109, in list_connected_probes
    allProbes = ConnectHelper.get_all_connected_probes(blocking=False)
  File "/home/x/usr/local/venv37zephyr/lib/python3.7/site-packages/pyocd-0.30.4.dev31-py3.7.egg/pyocd/core/helpers.py", line 82, in get_all_connected_probes
    allProbes = DebugProbeAggregator.get_all_connected_probes(unique_id=unique_id)
  File "/home/x/usr/local/venv37zephyr/lib/python3.7/site-packages/pyocd-0.30.4.dev31-py3.7.egg/pyocd/probe/aggregator.py", line 64, in get_all_connected_probes
    probes += cls.get_all_connected_probes(unique_id, is_explicit)
  File "/home/x/usr/local/venv37zephyr/lib/python3.7/site-packages/pyocd_pemicro-1.0.4-py3.7.egg/pyocd_pemicro/pemicro_probe.py", line 90, in get_all_connected_probes
    raise cls._convert_exception(exc) from exc
pyocd.core.exceptions.ProbeError: Unable to determinate running operation system (FreeBSD)
```

* Another issue is the binary blob library provided with the package. Is it Open-Source? Can I compile it somehow?

**Comment by cederom** [comment]
Here you go https://github.com/NXPmicro/pypemicro/pull/8 :-) Detection added to FreeBSD, OpenBSD and NetBSD :-)

Binary blobs of the library needs to be provided yet by the vendor - are they Open-Source so I can build and upload?

There are also other *BSD Unix systems out there. You may want to check them with `if "BSD" in platform.system()` even if no library is provided that will prevent faults on platforms where `pypemicro` is a hard dependency :-)

**Comment by cederom** [comment]
Is it possible to create a release @Gargy007 ? 0.1.6 does not work on FreeBSD and is a blocker for automated environment setup with pip :-(

**Comment by Gargy007** [comment]
Hi,
Im out of PC this week. I try to do it the next one.

Petr

Dne čt 15. 7. 2021 2:18 uživatel Tomasz CEDRO ***@***.***>
napsal:

**Comment by cederom** [comment]
Great news, thank you @Gargy007, enjoy your free time :-)

**Comment by Gargy007** [comment]
Hi Tom,
 sorry for big delay (summer/holiday time :-( ), but I finally updated the
package.

Have a nice day
Petr

čt 15. 7. 2021 v 18:23 odesílatel Tomasz CEDRO ***@***.***>
napsal:

**Comment by cederom** [comment]
TANK U SIR! =)
